### ISSUE TITLE
Use of AGPLv3 license

### ISSUE THREAD

**Issue by berendt** [SovereignCloudStack/cluster-stack-operator#4]
In new SCS projects I would prefer to see the AGPLv3 license instead of the ASL2.0 license. I think we would have documented this somewhere, but I can't find the document at the moment.

**Comment by berendt** [comment]
@garloff

**Comment by fkr** [comment]
I concur. More important: instead of simply importing the license, I'd like to see a public decision on the license with the rationale behind the licensing decision being documented.

**Comment by garloff** [comment]
https://docs.scs.community/community/license-considerations

**Comment by garloff** [comment]
We had discussed this early on in our project, which lead to above considerations:
* Reciprocal licenses have the advantage of disallowing proprietary forks (if the fork is not just used internally) and thus contribute to avoiding fragmentation.
* These licenses thus protect creators of open source projects better (at the expense of consumers needing to be more careful).
* The AGPL has a very broad definition of what constitutes releasing code and creating derivative works. This has the strongest anti-fragmentation effect, however also looks the most risky to corporate lawyers.

We may need to rediscuss our considerations to see how well they work in practice.
It may not be helpful to have considerations that are nice in theory but then not applicable in real-life.

Currently, we have almost all code under Apache-2.0, due to being connected to OIF or CNCF projects which both strongly favor Apache-2.0. We have some documentation (and scripts) under CC-BY-SA-4.0 which is a weak reciprocal license.

**Comment by garloff** [comment]
For cluster-stack-operator specifically, diverging from Apache-2.0 would not be a good choice:
* Cluster Stacks very closely integrates with cluster classes in the cluster API framework. This is all under Apache-2.0 and we want these projects to be able to share code, integrate, merge or whatever may happen in the future.
* The CNCF world is very strongly in favor of Apache-2.0 licenses to a degree that other code needs exceptions to be eligible to become CNCF projects.
* While we might argue that there would be somewhat less proliferation of projects (for better or worse) and stronger pressure to collaborate with less-permissive licensing, we are not in a position to change it. To have a chance to do something that has relevance in the CNCF ecosystem, we can not work with licensing that (for good or bad reasons) are not accepted by the audience.
* We also want contributions from others and make this a very open project with contributions from a broad community. A lot of this community would come out of the CNCF world and will much more easily work with Apache-2 license.
